spring.application.name=mantenedor
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.rgujyyfbnlaibqddlkca
spring.datasource.password=avqWvLfEne8737A9


spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
logging.level.org.springframework.security.web.*=debug


